# Generated by Django 5.0.6 on 2024-06-03 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplce', '0002_tax'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tax',
            options={'verbose_name_plural': 'tax'},
        ),
    ]
