# Generated by Django 5.0.6 on 2024-05-31 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_vendor_category_name_slug',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='uinque_vendor_category_product_slug',
        ),
    ]
