# Generated by Django 5.0.6 on 2024-05-31 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_category_unique_vendor_category_name_slug_and_more'),
        ('vendor', '0002_alter_vendor_is_approved'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('vendor', 'category_name', 'slug'), name='unique_vendor_category_name_slug'),
        ),
    ]
