# Generated by Django 5.0.6 on 2024-05-31 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_category_category_name_alter_category_slug'),
        ('vendor', '0002_alter_vendor_is_approved'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_vendor_category_name_slug',
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('vendor', 'category_name'), name='unique_vendor_category_name_slug'),
        ),
    ]
