# Generated by Django 5.0.6 on 2024-06-11 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'verbose_name': 'Orders', 'verbose_name_plural': 'Orders'},
        ),
    ]
