# Generated by Django 5.0.6 on 2024-06-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_ordermodel_payment_alter_ordermodel_phone_and_more'),
        ('vendor', '0008_remove_openinghours_unique_opening_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='total_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='vendors',
            field=models.ManyToManyField(blank=True, to='vendor.vendor'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='order_status',
            field=models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='New', max_length=50),
        ),
    ]
